const path = {
  HOME: "/",
  LOGIN: "/login",
  LOGIN_GOOGLE: "/auth/google",
  REGISTER: "/dang-ky",
  CATEGORY: "/danh-muc/:category",
  COLLECTION: "/bo-suu-tap/:collection",
  CART: "/cart",
  PRODUCT: "/product",
  PRODUCT_DETAIL: "/san-pham/:slug/:id",
  BLOG: "/blog",
  BLOG_DETAIL: "/blog/:id",
  CHECKOUT: "/checkout",
  ADMIN: "/admin",
  USER_MANAGEMENT: "user-management",
  CATEGORY_MANAGEMENT: "list-category",
  CATEGORY_ADD: "list-category/add",
  CATEGORY_EDIT: "list-category/:id/edit",
  PRODUCT_MANAGEMENT: "products",
  PRODUCT_VIEW: "products/view/:id",
  PRODUCT_ADD: "products/add",
  PRODUCT_EDIT: "products/:id/edit",
  PRODUCT_INVENTORY: "inventory/edit/:id/:params",
  COUPON_MANAGEMENT: "coupons",
  COUPON_EDIT: "coupons/:id/edit",
  COUPON_ADD: "coupons/add",
  COUPON_TYPE_MANAGEMENT: "coupons-types",
  COUPON_TYPE_EDIT: "coupons-types/:id/edit",
  COUPON_TYPE_ADD: "coupons-types/add",
  ORDER_MANAGEMENT: "order-management",
  ORDER_DETAILS_MANAGEMENT: "chi-tiet-don-hang/:code/:status",
  BLOG_MANAGEMENT: "blog-management",
  COMMENT_MANAGEMENT: "comment-management",
  ORDER: "/order",
  ORDER_DETAILS: "/order_details/:code",
  THANKYOU: "thankyou",
};

export default path;
